const CAT_LEVELS=[
  {n:"Voodoo",f:"voodoo",r:4.0},
  {n:"Virus",f:"virus",r:4.0},
  {n:"Weedcat",f:"weedcat",r:3.5},
  {n:"Puss in Boots",f:"puss-in-boots",r:4.0},
  {n:"Vapurr",f:"vapurr",r:4.0},
  {n:"Caustic",f:"caustic",r:3.0},
  {n:"Gecko Cat",f:"gecko-cat",r:1.5},
  {n:"Creeper",f:"creeper",r:3.5},
  {n:"Torracat",f:"torracat",r:3.5},
  {n:"Instacat",f:"instacat",r:3.5},
  {n:"Purrlion",f:"purrlion",r:3.5},
  {n:"El Tigre",f:"el-tigre",r:1.5},
  {n:"Cathulhu",f:"cathulhu",r:3.0},
  {n:"Jeopard",f:"jeopard",r:1.5},
  {n:"Bipolar Cat",f:"bipolar-cat",r:1.5},
  {n:"Chili Whisk",f:"chili-whisk",r:1.0},
  {n:"Copperclaw",f:"copperclaw",r:1.5},
  {n:"Blitzo",f:"blitzo",r:1.5},
  {n:"Cookie",f:"cookie",r:1.0},
  {n:"Esmeralda",f:"esmeralda",r:2.5},
  {n:"Nyan Cat",f:"nyan-cat",r:3.5},
  {n:"Ranni",f:"ranni",r:1.5},
  {n:"Niko",f:"niko",r:2.5},
  {n:"Purrrple",f:"purrrple",r:1.0},
  {n:"Meowdas",f:"meowdas",r:2.5},
  {n:"Cat2O",f:"cat2o",r:1.0},
  {n:"Pepe Paws",f:"pepe-paws",r:3.0},
  {n:"Caramel",f:"caramel",r:1.0},
  {n:"Endercat",f:"endercat",r:3.0},
  {n:"Ruby",f:"ruby",r:1.5},
  {n:"Cat Nukem",f:"cat-nukem",r:4.0},
  {n:"Jaddy",f:"jaddy",r:1.0},
  {n:"Bubblegum",f:"bubblegum",r:0.5},
  {n:"Phantom",f:"phantom",r:1.5},
  {n:"Vice Kitty",f:"vice-kitty",r:1.0},
  {n:"Oreo",f:"oreo",r:1.0},
  {n:"Nebula",f:"nebula",r:2.5},
  {n:"Cake",f:"cake",r:1.0},
  {n:"Silver Napper",f:"silver-napper",r:2.0},
  {n:"Vampkitty",f:"vampkitty",r:1.0},
  {n:"Yolkster",f:"yolkster",r:1.0},
  {n:"Fern",f:"fern",r:0.5},
  {n:"Celestia",f:"celestia",r:3.0},
  {n:"Goodbye Kitty",f:"goodbye-kitty",r:1.5},
  {n:"Mentos",f:"mentos",r:0.5},
  {n:"Misty Ash",f:"misty-ash",r:0.5},
  {n:"Azuki Siam",f:"azuki-siam",r:0.5},
  {n:"Garfield",f:"garfield",r:0.5},
  {n:"Obelisk",f:"obelisk",r:2.0},
  {n:"Salem",f:"salem",r:1.0}
];
