const LEVELS=[
  {n:"Brownie",f:"brownie",r:4.0},
  {n:"Tide Pod",f:"tide-pod",r:4.0},
  {n:"Lemon Juice",f:"lemon-juice",r:4.0},
  {n:"Cranberry",f:"cranberry",r:4.0},
  {n:"Frogwave",f:"frogwave",r:4.0},
  {n:"Lily Pond",f:"lily-pond",r:4.0},
  {n:"Peach",f:"peach",r:4.0},
  {n:"Toadberry",f:"toadberry",r:4.0},
  {n:"Sky Leaper",f:"sky-leaper",r:4.0},
  {n:"Sea Breeze",f:"sea-breeze",r:4.0},
  {n:"Frogtart",f:"frogtart",r:3.0},
  {n:"Banana Pox",f:"banana-pox",r:3.0},
  {n:"Melon",f:"melon",r:3.0},
  {n:"Ectobloom",f:"ectobloom",r:2.5},
  {n:"Ectofrog",f:"ectofrog",r:2.5},
  {n:"Starry Night",f:"starry-night",r:2.5},
  {n:"Duskhopper",f:"duskhopper",r:2.5},
  {n:"Sarutoad",f:"sarutoad",r:2.5},
  {n:"Void Hopper",f:"void-hopper",r:2.5},
  {n:"Minty Bloom",f:"minty-bloom",r:2.5},
  {n:"Lemon Drop",f:"lemon-drop",r:2.5},
  {n:"Ramune",f:"ramune",r:2.5},
  {n:"Poison",f:"poison",r:2.5},
  {n:"Bronze",f:"bronze",r:2.0},
  {n:"Silver",f:"silver",r:2.0},
  {n:"Desert Frog",f:"desert-frog",r:1.5},
  {n:"Ms. Toad",f:"ms-toad",r:1.5},
  {n:"Cupid",f:"cupid",r:1.5},
  {n:"Toadstool",f:"toadstool",r:1.5},
  {n:"Prince Ribbit",f:"prince-ribbit",r:1.5},
  {n:"Boingo",f:"boingo",r:1.5},
  {n:"Hopberry",f:"hopberry",r:1.5},
  {n:"Icefrog",f:"icefrog",r:1.0},
  {n:"Pond Fairy",f:"pond-fairy",r:1.0},
  {n:"Trixie",f:"trixie",r:1.0},
  {n:"Tesla Frog",f:"tesla-frog",r:1.0},
  {n:"Lava Leap",f:"lava-leap",r:1.0},
  {n:"Tree Frog",f:"tree-frog",r:0.5},
  {n:"Sweet Dream",f:"sweet-dream",r:0.5},
  {n:"Melty Butter",f:"melty-butter",r:0.5},
  {n:"Frogmaid",f:"frogmaid",r:0.5},
  {n:"Lilie Pond",f:"lilie-pond",r:0.5},
  {n:"Count Croakula",f:"count-croakula",r:0.5},
  {n:"Honeyhop",f:"honeyhop",r:0.5},
  {n:"Lucifrog",f:"lucifrog",r:0.5},
  {n:"Puddles",f:"puddles",r:0.5},
  {n:"Rocky Hopper",f:"rocky-hopper",r:0.5},
  {n:"Zodiak Croak",f:"zodiak-croak",r:0.5},
  {n:"Brewtoad",f:"brewtoad",r:0.5},
  {n:"Happy Pepe",f:"happy-pepe",r:0.5}
];
